# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from robot_msg/robot_pose_array.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import robot_msg.msg
import std_msgs.msg

class robot_pose_array(genpy.Message):
  _md5sum = "b5025b9975c3a323219809cc70bf1c63"
  _type = "robot_msg/robot_pose_array"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """robot_msg/robot_pose[] robot_pose_array

================================================================================
MSG: robot_msg/robot_pose
std_msgs/Int8 ID
geometry_msgs/Point position
float32 yaw

================================================================================
MSG: std_msgs/Int8
int8 data

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z
"""
  __slots__ = ['robot_pose_array']
  _slot_types = ['robot_msg/robot_pose[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       robot_pose_array

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(robot_pose_array, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.robot_pose_array is None:
        self.robot_pose_array = []
    else:
      self.robot_pose_array = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.robot_pose_array)
      buff.write(_struct_I.pack(length))
      for val1 in self.robot_pose_array:
        _v1 = val1.ID
        _x = _v1.data
        buff.write(_get_struct_b().pack(_x))
        _v2 = val1.position
        _x = _v2
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _x = val1.yaw
        buff.write(_get_struct_f().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.robot_pose_array is None:
        self.robot_pose_array = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.robot_pose_array = []
      for i in range(0, length):
        val1 = robot_msg.msg.robot_pose()
        _v3 = val1.ID
        start = end
        end += 1
        (_v3.data,) = _get_struct_b().unpack(str[start:end])
        _v4 = val1.position
        _x = _v4
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        start = end
        end += 4
        (val1.yaw,) = _get_struct_f().unpack(str[start:end])
        self.robot_pose_array.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.robot_pose_array)
      buff.write(_struct_I.pack(length))
      for val1 in self.robot_pose_array:
        _v5 = val1.ID
        _x = _v5.data
        buff.write(_get_struct_b().pack(_x))
        _v6 = val1.position
        _x = _v6
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _x = val1.yaw
        buff.write(_get_struct_f().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.robot_pose_array is None:
        self.robot_pose_array = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.robot_pose_array = []
      for i in range(0, length):
        val1 = robot_msg.msg.robot_pose()
        _v7 = val1.ID
        start = end
        end += 1
        (_v7.data,) = _get_struct_b().unpack(str[start:end])
        _v8 = val1.position
        _x = _v8
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        start = end
        end += 4
        (val1.yaw,) = _get_struct_f().unpack(str[start:end])
        self.robot_pose_array.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3d = None
def _get_struct_3d():
    global _struct_3d
    if _struct_3d is None:
        _struct_3d = struct.Struct("<3d")
    return _struct_3d
_struct_b = None
def _get_struct_b():
    global _struct_b
    if _struct_b is None:
        _struct_b = struct.Struct("<b")
    return _struct_b
_struct_f = None
def _get_struct_f():
    global _struct_f
    if _struct_f is None:
        _struct_f = struct.Struct("<f")
    return _struct_f
