// Generated by gencpp from file robot_msg/robot_pose.msg
// DO NOT EDIT!


#ifndef ROBOT_MSG_MESSAGE_ROBOT_POSE_H
#define ROBOT_MSG_MESSAGE_ROBOT_POSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Int8.h>
#include <geometry_msgs/Point.h>

namespace robot_msg
{
template <class ContainerAllocator>
struct robot_pose_
{
  typedef robot_pose_<ContainerAllocator> Type;

  robot_pose_()
    : ID()
    , position()
    , yaw(0.0)  {
    }
  robot_pose_(const ContainerAllocator& _alloc)
    : ID(_alloc)
    , position(_alloc)
    , yaw(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Int8_<ContainerAllocator>  _ID_type;
  _ID_type ID;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _position_type;
  _position_type position;

   typedef float _yaw_type;
  _yaw_type yaw;





  typedef boost::shared_ptr< ::robot_msg::robot_pose_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_msg::robot_pose_<ContainerAllocator> const> ConstPtr;

}; // struct robot_pose_

typedef ::robot_msg::robot_pose_<std::allocator<void> > robot_pose;

typedef boost::shared_ptr< ::robot_msg::robot_pose > robot_posePtr;
typedef boost::shared_ptr< ::robot_msg::robot_pose const> robot_poseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_msg::robot_pose_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_msg::robot_pose_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_msg::robot_pose_<ContainerAllocator1> & lhs, const ::robot_msg::robot_pose_<ContainerAllocator2> & rhs)
{
  return lhs.ID == rhs.ID &&
    lhs.position == rhs.position &&
    lhs.yaw == rhs.yaw;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_msg::robot_pose_<ContainerAllocator1> & lhs, const ::robot_msg::robot_pose_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_msg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_msg::robot_pose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_msg::robot_pose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msg::robot_pose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msg::robot_pose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msg::robot_pose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msg::robot_pose_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_msg::robot_pose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c2b2afa426c38cad763bf7a208a1669f";
  }

  static const char* value(const ::robot_msg::robot_pose_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc2b2afa426c38cadULL;
  static const uint64_t static_value2 = 0x763bf7a208a1669fULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_msg::robot_pose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_msg/robot_pose";
  }

  static const char* value(const ::robot_msg::robot_pose_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_msg::robot_pose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Int8 ID\n"
"geometry_msgs/Point position\n"
"float32 yaw\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Int8\n"
"int8 data\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::robot_msg::robot_pose_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_msg::robot_pose_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ID);
      stream.next(m.position);
      stream.next(m.yaw);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct robot_pose_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_msg::robot_pose_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_msg::robot_pose_<ContainerAllocator>& v)
  {
    s << indent << "ID: ";
    s << std::endl;
    Printer< ::std_msgs::Int8_<ContainerAllocator> >::stream(s, indent + "  ", v.ID);
    s << indent << "position: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
    s << indent << "yaw: ";
    Printer<float>::stream(s, indent + "  ", v.yaw);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_MSG_MESSAGE_ROBOT_POSE_H
